// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBook = "book"

// Book mapped from table <book>
type Book struct {
	Book  string    `gorm:"column:book;primaryKey;comment:book name" json:"book"`  // book name
	Price int32     `gorm:"column:price;not null;comment:book price" json:"price"` // book price
	CTime time.Time `gorm:"column:c_time" json:"c_time"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
