// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMyModel = "model"

// MyModel mapped from table <model>
type MyModel struct {
	ID               string `gorm:"column:id;primaryKey" json:"id"`
	Name             string `gorm:"column:name;not null" json:"name"`
	ProjectID        string `gorm:"column:project_id;not null" json:"project_id"`
	ParentModelID    string `gorm:"column:parent_model_id;not null" json:"parent_model_id"`
	ModelTypeID      string `gorm:"column:model_type_id;not null" json:"model_type_id"`
	Description      string `gorm:"column:description;not null" json:"description"`
	Position         string `gorm:"column:position;not null" json:"position"`
	Icon             string `gorm:"column:icon;not null" json:"icon"`
	TableName_       string `gorm:"column:table_name;not null" json:"table_name"`
	Sort             int32  `gorm:"column:sort;not null" json:"sort"`
	IsHidden         bool   `gorm:"column:is_hidden;not null" json:"is_hidden"`
	IsDefault        bool   `gorm:"column:is_default;not null" json:"is_default"`
	IsNet            bool   `gorm:"column:is_net;not null" json:"is_net"`
	FrontendTemplate string `gorm:"column:frontend_template;not null" json:"frontend_template"`
	ListModelIds     string `gorm:"column:list_model_ids;not null" json:"list_model_ids"`
	Script           string `gorm:"column:script;not null" json:"script"`
	ViewRelations    string `gorm:"column:view_relations;not null;comment:视图关联关系" json:"view_relations"`       // 视图关联关系
	IsAutoFlush      bool   `gorm:"column:is_auto_flush;not null;comment:是否自动刷新" json:"is_auto_flush"`         // 是否自动刷新
	SSHConnectConf   int32  `gorm:"column:ssh_connect_conf;not null;comment:ssh连接配置项" json:"ssh_connect_conf"` // ssh连接配置项
	TemplateIds      string `gorm:"column:template_ids;not null" json:"template_ids"`
}

// TableName MyModel's table name
func (*MyModel) TableName() string {
	return TableNameMyModel
}
