// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDevice = "device"

// Device mapped from table <device>
type Device struct {
	ID               int64     `gorm:"column:id;primaryKey" json:"id"`
	Name             string    `gorm:"column:name;not null" json:"name"`
	ProjectID        string    `gorm:"column:project_id;not null" json:"project_id"`
	Status           string    `gorm:"column:status;not null" json:"status"`
	Platform         string    `gorm:"column:platform;not null" json:"platform"`
	Version          string    `gorm:"column:version;not null" json:"version"`
	Sn               string    `gorm:"column:sn;not null" json:"sn"`
	IP               string    `gorm:"column:ip;not null" json:"ip"`
	SSHPort          string    `gorm:"column:ssh_port;not null" json:"ssh_port"`
	APIPort          string    `gorm:"column:api_port;not null" json:"api_port"`
	AssetNo          string    `gorm:"column:asset_no;not null" json:"asset_no"`
	AssetPrice       float64   `gorm:"column:asset_price;not null" json:"asset_price"`
	PurchTime        time.Time `gorm:"column:purch_time;not null" json:"purch_time"`
	OnlineStatus     string    `gorm:"column:online_status;not null" json:"online_status"`
	StartU           int32     `gorm:"column:start_u;not null" json:"start_u"`
	OccupiedU        int32     `gorm:"column:occupied_u;not null" json:"occupied_u"`
	MaintenanceStart time.Time `gorm:"column:maintenance_start;not null" json:"maintenance_start"`
	MaintenanceEnd   time.Time `gorm:"column:maintenance_end;not null" json:"maintenance_end"`
	Operator         string    `gorm:"column:operator;not null" json:"operator"`
	OperatorPhone    string    `gorm:"column:operator_phone;not null" json:"operator_phone"`
	Purpose          string    `gorm:"column:purpose;not null" json:"purpose"`
	ProviderName     string    `gorm:"column:provider_name;not null" json:"provider_name"`
	DevStatus        string    `gorm:"column:dev_status;not null" json:"dev_status"`
	LicenseStatus    string    `gorm:"column:license_status;not null" json:"license_status"`
	WebURL           string    `gorm:"column:web_url;not null" json:"web_url"`
	AccessPasswordID string    `gorm:"column:access_password_id;not null" json:"access_password_id"`
	AuthPasswordID   string    `gorm:"column:auth_password_id;not null" json:"auth_password_id"`
	DeviceGroupID    string    `gorm:"column:device_group_id;not null" json:"device_group_id"`
	SynGroupID       string    `gorm:"column:syn_group_id;not null" json:"syn_group_id"`
	SynStatus        string    `gorm:"column:syn_status;not null" json:"syn_status"`
	SnmpStatus       string    `gorm:"column:snmp_status;not null" json:"snmp_status"`
	LogStatus        string    `gorm:"column:log_status;not null" json:"log_status"`
	SynTime          time.Time `gorm:"column:syn_time;not null" json:"syn_time"`
	HostName         string    `gorm:"column:host_name;not null" json:"host_name"`
	RawConfigs       string    `gorm:"column:raw_configs;not null" json:"raw_configs"`
	NetacID          string    `gorm:"column:netac_id;not null" json:"netac_id"`
	ExternalPolicyID string    `gorm:"column:external_policy_id;not null" json:"external_policy_id"`
	MetricVersion    string    `gorm:"column:metric_version;not null" json:"metric_version"`
	StateSynTime     string    `gorm:"column:state_syn_time;not null" json:"state_syn_time"`
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
