// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Email       string    `gorm:"column:email;not null" json:"email"`
	Password    string    `gorm:"column:password;not null" json:"password"`
	PhoneNumber string    `gorm:"column:phone_number;not null" json:"phone_number"`
	Username    string    `gorm:"column:username;not null" json:"username"`
	FirstName   string    `gorm:"column:first_name;not null" json:"first_name"`
	LastName    string    `gorm:"column:last_name;not null" json:"last_name"`
	Century     string    `gorm:"column:century;not null" json:"century"`
	Date        time.Time `gorm:"column:date;not null" json:"date"`
	CompanyCode string    `gorm:"column:company_code;not null" json:"company_code"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
